apiVersion: skaffold/v4beta6
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/**/*.yaml
metadata:
  name: dine-ease-backend
build:
  artifacts:
    - image: mujtabashafiq/dine-ease-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: mujtabashafiq/dine-ease-dining-plans
      context: dining-plans
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: mujtabashafiq/dine-ease-login-gateway
      context: login-gateway
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: mujtabashafiq/dine-ease-mail
      context: mail
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: mujtabashafiq/dine-ease-map
      context: map
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: mujtabashafiq/dine-ease-users
      context: users
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: mujtabashafiq/dine-ease-subscriptions
      context: subscriptions
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: mujtabashafiq/dine-ease-reviews
      context: reviews
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: mujtabashafiq/dine-ease-restaurants
      context: restaurants
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .