apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: mujtabashafiq/dine-ease-users
          env:
            - name: MONGO_URI
              # value: "mongodb://users-mongo-srv:27017/users"
              value: users
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: dine-ease
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: JWT_KEY
            - name: MONGO_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: MONGO_CONNECTION
            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: AWS_S3_ACCESS_KEY_ID
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: AWS_S3_SECRET_ACCESS_KEY
            - name: AWS_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: AWS_S3_REGION
---
apiVersion: v1
kind: Service
metadata:
  name: users-srv
spec:
  selector:
    app: users
  ports:
    - name: users
      protocol: TCP
      port: 3000
      targetPort: 3000
