apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.7
          ports:
            - containerPort: 7700
          volumeMounts:
            - name: meilisearch-data
              mountPath: /data.ms
      volumes:
      - name: meilisearch-data
        persistentVolumeClaim:
          claimName: meilisearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch-srv
spec:
  selector:
    app: meilisearch
  ports:
    - name: meili
      port: 7700
      targetPort: 7700