apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: dine-ease.dev
      http:
        paths:
          - path: /api/auth/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /api/login/?(.*)
            pathType: Prefix
            backend:
              service:
                name: login-gateway-srv
                port:
                  number: 3000
          - path: /api/mail/?(.*)
            pathType: Prefix
            backend:
              service:
                name: mail-srv
                port:
                  number: 3000
          - path: /api/user/?(.*)
            pathType: Prefix
            backend:
              service:
                name: users-srv
                port:
                  number: 3000
          - path: /api/notifications
            pathType: Prefix
            backend:
              service:
                name: notifications-srv
                port:
                  number: 3000
          - path: /socket.io/notifications
            pathType: Prefix
            backend:
              service:
                name: notifications-srv
                port:
                  number: 3000
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000