apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: mujtabashafiq/dine-ease:login
          env:
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: dine-ease
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: login-srv
spec:
  selector:
    app: login
  ports:
    - name: login
      protocol: TCP
      port: 3000
      targetPort: 3000
