apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: dine-ease/users
          env:
            - name: MONGO_URI
              value: "mongodb://users-mongo-srv:27017/users"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: EMAIL_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: email-jwt-secret
                  key: EMAIL_JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: users-srv
spec:
  selector:
    app: users
  ports:
    - name: users
      protocol: TCP
      port: 3000
      targetPort: 3000
