apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map
  template:
    metadata:
      labels:
        app: map
    spec:
      containers:
        - name: map
          image: mujtabashafiq/dine-ease-map
          env:
            - name: MONGO_URI
              # value: "mongodb://map-mongo-srv:27017/map"
              value: map
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: dine-ease
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: JWT_KEY
            - name: MONGO_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: MONGO_CONNECTION
---
apiVersion: v1
kind: Service
metadata:
  name: map-srv
spec:
  selector:
    app: map
  ports:
    - name: map
      protocol: TCP
      port: 3000
      targetPort: 3000
