apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: mujtabashafiq/dine-ease-notifications
          env:
            - name: MONGO_URI
              # value: "mongodb://notifications-mongo-srv:27017/notifications"
              value: notifications
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: dine-ease
            - name: REDIS_HOST
              value: redis://notifications-redis-srv
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: JWT_KEY
            - name: MONGO_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: MONGO_CONNECTION
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-srv
spec:
  selector:
    app: notifications
  ports:
    - name: notifications
      protocol: TCP
      port: 3000
      targetPort: 3000
