apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-redis-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-redis
  template:
    metadata:
      labels:
        app: notifications-redis
    spec:
      containers:
        - name: notifications-redis
          image: redis
          command:
            - redis-server
            - "--port"
            - "6380"  # Setting Redis to listen on port 6380
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-redis-srv
spec:
  selector:
    app: notifications-redis
  ports:
    - name: db
      protocol: TCP
      port: 6380
      targetPort: 6380
  type: NodePort