apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mujtabashafiq/dine-ease-auth
          env:
            - name: MONGO_URI
              # value: "mongodb://auth-mongo-srv:27017/auth"
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: MONGO_AUTH_URI
            - name: EMAIL_JWT_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: dine-ease
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: JWT_KEY
            - name: EMAIL_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: EMAIL_JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
