apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - name: reviews
          image: mujtabashafiq/dine-ease-reviews
          env:
            - name: MONGO_URI
              # value: "mongodb://reviews-mongo-srv:27017/reviews"
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: MONGO_REVIEWS_URI
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: dine-ease
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: JWT_KEY
            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: AWS_S3_ACCESS_KEY_ID
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: AWS_S3_SECRET_ACCESS_KEY
            - name: AWS_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: AWS_S3_REGION
            - name: AWS_S3_REVIEWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: dine-ease-secrets
                  key: AWS_S3_REVIEWS_BUCKET
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-srv
spec:
  selector:
    app: reviews
  ports:
    - name: reviews
      protocol: TCP
      port: 3000
      targetPort: 3000
